global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-app'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

  - job_name: 'toxiproxy'
    static_configs:
      - targets: ['toxiproxy:8474']
    metrics_path: '/metrics'
    scrape_interval: 5s